language: r
sudo: false
cache: packages
r_github_packages:
- leeper/prediction
r_packages:
- knitr
- rmarkdown
- testthat
- covr
- ggplot2
- gapminder
- nnet
- ordinal
- sandwich
- survey
- stargazer
after_success:
- Rscript -e 'library("covr");codecov()'
